### DISCUSSION TITLE
Instruccions for flashing and mantaining using the ESPHOME addon in HA

### DISCUSSION THREAD

**Discussion by mshrem** [JanM321/esphome-lg-controller#55] [General]
Hello its been a while since i was able to flash my units but i found a way to use the ESPHOME addon to flash the device on HA directly. You can also check the logs wiresly on the addon or upload any firmware changes and updates.

1 You will need a couple of addons the ESPHome addon , and another addon to put some files inside the Esphome folder in HA (File editor or Samba addon works in here)

2 Copy the contents of esphome/components/ from this repository to the /homeassistant/esphome/components 

![image](https://github.com/JanM321/esphome-lg-controller/assets/560713/24d068d9-ab57-4423-af82-5140ce6d82f6)

3 Go to the Esphome tab in HA and add a new device. 
- Name your device 
- Press skip this step 
- Select ESP32 and use recommended settings
- You should get a Congratulations created! message 
- Skip again 

4 Go to the edit button so you can edit your newly created.yaml file 

5 Add the following before the first line and edit to your liking. 

```
substitutions:
  # Unique device ID in HA
  deviceid: "lglivingroom" # XXX
  # Unique device name in HA (sensor names will be prefixed by this name)
  devicename: "LG Living Room" # XXX
  # The input temperature sensor in HA.
  temperature_sensor_entity_id: sensor.my_sensor # XXX
  # Set to "true" if the temperature sensor and Home Assistant use Fahrenheit instead of Celsius.
  fahrenheit: "false" # XXX
  # If multiple controllers are connected to a single indoor unit, only one of them should be
  # configured as "master controller". Slave mode is a new and experimental feature for this
  # ESPHome controller and might not work well.
  # If you're connecting a single controller, this should be set to "false".
  is_slave_controller: "false"
```

6 Add the following at the end of the file 

```
uart:
  - id: ac_serial
    tx_pin: GPIO25
    rx_pin: GPIO26 # Keep in sync with RxPin in lg-controller.h
    baud_rate: 104

sensor:
  - id: temp_sensor
    platform: homeassistant
    internal: true
    entity_id: ${temperature_sensor_entity_id}
  - platform: uptime
    name: Uptime

external_components:
  - source: components
    components: [lg_controller]

climate:
  - platform: lg_controller
    name: ""
    id: ${deviceid}
    fahrenheit: ${fahrenheit}
    is_slave_controller: ${is_slave_controller}
    temperature_sensor: temp_sensor
    vane1:
      name: Airflow 1 Up/Down
      id: vane_position_1
      icon: mdi:arrow-up-down
    vane2:
      name: Airflow 2 Up/Down
      id: vane_position_2
      icon: mdi:arrow-up-down
    vane3:
      name: Airflow 3 Up/Down
      id: vane_position_3
      icon: mdi:arrow-up-down
    vane4:
      name: Airflow 4 Up/Down
      id: vane_position_4
      icon: mdi:arrow-up-down
    overheating:
      name: Over Heating
      id: overheating
      icon: mdi:heating-coil
    fan_speed_slow:
      name: Fan Speed Slow
      id: fan_speed_slow
      icon: mdi:fan-chevron-down
      mode: box
    fan_speed_low:
      name: Fan Speed Low
      id: fan_speed_low
      icon: mdi:fan-speed-1
      mode: box
    fan_speed_medium:
      name: Fan Speed Medium
      id: fan_speed_medium
      icon: mdi:fan-speed-2
      mode: box
    fan_speed_high:
      name: Fan Speed High
      id: fan_speed_high
      icon: mdi:fan-speed-3
      mode: box
    sleep_timer:
      name: "Sleep Timer (minutes)"
      id: sleep_timer
      icon: mdi:timer-outline
      mode: box
    error_code:
      name: Error Code
      id: error_code
      icon: mdi:alert-circle-outline
    pipe_temp_in:
      name: Pipe Temperature In
      id: pipe_temperature_in
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    pipe_temp_mid:
      name: Pipe Temperature Mid
      id: pipe_temperature_mid
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    pipe_temp_out:
      name: Pipe Temperature Out
      id: pipe_temperature_out
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    defrost:
      name: Defrost
      id: defrost
      icon: mdi:snowflake-melt
    preheat:
      name: Preheat
      id: preheat
      icon: mdi:heat-wave
    outdoor:
      name: Outdoor Unit
      id: outdoor
      icon: mdi:fan
    auto_dry_active:
      name: Auto Dry Active
      id: auto_dry_active
      icon: mdi:fan-clock
    purifier:
      name: Air Purifier
      id: air_purifier
      icon: mdi:pine-tree
    internal_thermistor:
      name: Internal Thermistor
      id: internal_thermistor
      icon: mdi:thermometer
    auto_dry:
      name: Auto Dry
      id: auto_dry
      icon: mdi:fan-clock
```

7 Save your changes.

8 3 dots and click install 

9 Select plug into this computer 

10 Connect your ESP board with a USB cable and select it 

11 Wait for the flash to finish 

12 Profit you should be able to read it with the ESPHOME addon

**Comment by ghost** [comment]
I am using latest HA ( core ver. 2024.5.5 ) and latest ESPHOME Addon ( ver. 2024.5.4 ) . During compilation I got few errors like :
- error: 'isnan' was not declared in this scope
- error: 'ESP' was not declared in this scope
- error: 'digitalRead' was not declared in this scope
- error: 'LOW' was not declared in this scope
Fix which worked for me,  I have to add to lg-controller.h two following lines at beginning 
#include "math.h"
#include "Arduino.h"
After that , no errors , and My ESP32 works quite well

**Comment by SiboutVanLoo** [comment]
Update:

# Second part to paste under the original ESPHOME YAML

uart:
  - id: ac_serial
    tx_pin: GPIO25
    #rx_pin: GPIO26 # Keep in sync with RxPin in lg-controller.h mentioned twice, so comment this one out
    baud_rate: 104

sensor:
  - id: temp_sensor
    platform: homeassistant
    internal: true
    entity_id: ${temperature_sensor_entity_id}
  - platform: uptime
    name: Uptime

# Make shure to copy the "lg_controller folder in your local files see path used 

external_components:
  - source: /config/esphome/custom_components #this path
    components: 
      - lg_controller

climate:
  - platform: lg_controller
    name: ""
    id: ${deviceid}
    fahrenheit: ${fahrenheit}
    is_slave_controller: ${is_slave_controller}
    temperature_sensor: temp_sensor
    rx_pin: GPIO26 #Just a little shift avoiding errors
    vane1:
      name: Airflow 1 Up/Down
      id: vane_position_1
      icon: mdi:arrow-up-down
    vane2:
      name: Airflow 2 Up/Down
      id: vane_position_2
      icon: mdi:arrow-up-down
    vane3:
      name: Airflow 3 Up/Down
      id: vane_position_3
      icon: mdi:arrow-up-down
    vane4:
      name: Airflow 4 Up/Down
      id: vane_position_4
      icon: mdi:arrow-up-down
    overheating:
      name: Over Heating
      id: overheating
      icon: mdi:heating-coil
    fan_speed_slow:
      name: Fan Speed Slow
      id: fan_speed_slow
      icon: mdi:fan-chevron-down
      mode: box
    fan_speed_low:
      name: Fan Speed Low
      id: fan_speed_low
      icon: mdi:fan-speed-1
      mode: box
    fan_speed_medium:
      name: Fan Speed Medium
      id: fan_speed_medium
      icon: mdi:fan-speed-2
      mode: box
    fan_speed_high:
      name: Fan Speed High
      id: fan_speed_high
      icon: mdi:fan-speed-3
      mode: box
    sleep_timer:
      name: "Sleep Timer (minutes)"
      id: sleep_timer
      icon: mdi:timer-outline
      mode: box
    error_code:
      name: Error Code
      id: error_code
      icon: mdi:alert-circle-outline
    pipe_temp_in:
      name: Pipe Temperature In
      id: pipe_temperature_in
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    pipe_temp_mid:
      name: Pipe Temperature Mid
      id: pipe_temperature_mid
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    pipe_temp_out:
      name: Pipe Temperature Out
      id: pipe_temperature_out
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    defrost:
      name: Defrost
      id: defrost
      icon: mdi:snowflake-melt
    preheat:
      name: Preheat
      id: preheat
      icon: mdi:heat-wave
    outdoor:
      name: Outdoor Unit
      id: outdoor
      icon: mdi:fan
    auto_dry_active:
      name: Auto Dry Active
      id: auto_dry_active
      icon: mdi:fan-clock
    purifier:
      name: Air Purifier
      id: air_purifier
      icon: mdi:pine-tree
    internal_thermistor:
      name: Internal Thermistor
      id: internal_thermistor
      icon: mdi:thermometer
    auto_dry:
      name: Auto Dry
      id: auto_dry
      icon: mdi:fan-clock

**Comment by TerryFrench** [comment]
You can also skip copying the files.  Just use this for external_components 
And if you are afraid this might go away some day, fork it and point to your fork.


``` yaml
external_components:
  - source: github://JanM321/esphome-lg-controller
    components: ["lg_controller"]

```

**Comment by Adam1986** [comment]
@TerryFrench - thanks so much for doing this guide, I want to setup my ESP32's in this manner via ESPHome when they arrive.

I was intending on doing it something like the below, but unsure if it will work now, as you seem to have split out a lot of the config into the main YAML that you flash onto the ESP32.  So hopefully you can shed some light?

So say for my lounge air conditioning unit I have the following YAML:

```
# You should make sure all lines marked with XXX match your setup.

substitutions:
  # Unique device ID in HA
  deviceid: "loungeunit" # XXX
  # Unique device name in HA (sensor names will be prefixed by this name)
  devicename: "Lounge Unit" # XXX
  # The input temperature sensor in HA.
  temperature_sensor_entity_id: sensor.invalid # XXX
  # Set to "true" if the temperature sensor and Home Assistant use Fahrenheit instead of Celsius.
  fahrenheit: "false" # XXX
  # If multiple controllers are connected to a single indoor unit, only one of them should be
  # configured as "master controller". Slave mode is a new and experimental feature for this
  # ESPHome controller and might not work well.
  # If you're connecting a single controller, this should be set to "false".
  is_slave_controller: "false"

# Encryption key for HA. See https://esphome.io/components/api.html.
api:
  encryption:
    key: "encryptionkey" # XXX

wifi:
  ssid: "ssid" # XXX
  password: "passphrase" # XXX

  manual_ip:
    static_ip: 192.168.0.90 # XXX
    gateway: 192.168.0.1 # XXX
    subnet: 255.255.255.0 # XXX
    dns1: 192.168.0.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${deviceid} Fallback"
    password: "password" # XXX

captive_portal:

ota:
  platform: esphome
  password: ""

logger:
  level: DEBUG

<<: !include base-lg-ac.yaml
```

I've renamed base.yaml to base-lg-ac.yaml and that is just sat in the same root directory as the file above (esphome):

```
ls -l
total 20
drwxr-xr-x 2 root root 4096 Nov 25 15:57 archive
-rw-r--r-- 1 root root 3602 Nov 25 15:57 base-lg-ac.yaml
drwxr-xr-x 3 root root 4096 Nov 25 14:12 components
-rw-r--r-- 1 root root 1382 Nov 25 15:58 template.yaml
-rw-r--r-- 1 root root 1439 Nov 26 15:10 lounge-ac.yaml
```

Then I've put the 3 files here from the repository: /esphome/components/lg_controller:

```
ls -l
total 72
-rw-r--r-- 1 root root  6334 Nov 22 07:29 climate.py
-rw-r--r-- 1 root root     0 Nov 22 07:29 __init__.py
-rw-r--r-- 1 root root 59928 Nov 22 07:29 lg-controller.h
```

Hoping this will work as I have 5 units at my house to setup, along with 5 at my brothers that I will setup another ESPHome instance on with the identical setup.
