### ISSUE TITLE
Support connecting multiple controllers

### ISSUE THREAD

**Issue by JanM321** [JanM321/esphome-lg-controller#34]
The ESPHome controller currently assumes there's a single wired controller connected to the AC and it ignores messages on the bus from other controllers, even though the LG controllers support having one controller as 'master' and another as 'slave'.

Because the ESPHome controller is already acting as 'master' controller, the easiest way to fix this is to start processing messages from 'slave' controllers instead of ignoring them. This would let us connect a second LG controller in 'slave' mode.

The next step is to add an option to put the ESPHome controller itself in 'slave' mode. In this mode it would send 'slave' messages and respond to 'master' messages.

I have to look into this in more detail to see how my LG controllers behave when working with other controllers. I expect this to be straight-forward, but I want to see how the LG controllers handle things like room temperature etc.

**Comment by JanM321** [comment]
I added a YAML option to configure the ESPHome controller itself as 'slave' and the controller will now process messages from other controllers.

I don't use this with my own units so there might be some issues. Feedback welcome.

**Comment by djsys** [comment]
Hello,

I am working on integrating an **LG CM24 N14** indoor unit with **UUB1 U20** outdoor unit using the ESPHome-based **LG AC Wired Controller** project for LG HVAC systems. [community.home-assistant]
The wired controller I expect to use is an **LG PREMTB001**, and the project documentation indicates that LG wired controllers use a very slow serial bus at **104 bps, 8N1**, over the three-wire connector, with support for master/slave controller setups. [github](https://github.com/JanM321/esphome-lg-controller/blob/main/README.md)

I had a PCB manufactured for an **ESP32-C3**, but for testing I am currently using an **ESP WROOM-32**.  
My current pin assignment is:
- `gpio_rx: 16`
- `gpio_tx: 17`

Here is the YAML configuration I am flashing:

```yaml
# You should make sure all lines marked with XXX match your setup.
substitutions:
  deviceid: "lgClimxxxxxxx"
  devicename: "lgclim"
  device_friendly_name: djsys LG climate
  device_description: "climati LG CM24 N14"
  temperature_sensor_entity_id: "sensor.motiondetecsalon_device_temperature"
  device_ip: 192.168.0.13
  device_gateway: 192.168.0.1
  device_dns: 192.168.0.1
  device_dns_2: 192.168.0.1
  gpio_rx: 16
  gpio_tx: 17
  fahrenheit: "false"
  is_slave_controller: "true"

esphome:
  name: ${devicename}
  friendly_name: ${device_friendly_name}
  comment: ${device_description}

esp32:
  board: esp32dev
  framework:
    type: arduino

api:
  encryption:
    key: !secret key_lg_climat

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: ${device_dns}
    dns2: ${device_dns_2}
  ap:
    ssid: "recovery_${devicename}"
    password: !secret ap_password

web_server:
  port: 80

ota:
  platform: esphome
  password: !secret ota_password

logger:
  level: DEBUG

uart:
  id: uart_2
  tx_pin: ${gpio_tx}
  baud_rate: 104
  parity: NONE
  stop_bits: 1
  data_bits: 8
  rx_buffer_size: 256
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      timeout: 50ms
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');

sensor:
  - platform: homeassistant
    internal: true
    name: "temperature salon"
    id: temp_salon_copy
    entity_id: ${temperature_sensor_entity_id}
  - platform: uptime
    name: Uptime

external_components:
  - source:
      type: local
      path: /config/custom_components
    components:
      [ lg_controller ]

climate:
  - platform: lg_controller
    id: lg_ac
    name: "Clim Villa Jade"
    uart_id: uart_2
    rx_pin: ${gpio_rx}
    fahrenheit: ${fahrenheit}
    is_slave_controller: ${is_slave_controller}
    temperature_sensor: temp_salon_copy
```

The log currently shows the following behavior:

```text
[21:29:49.314][D][lg-controller:1360]: update
[21:29:49.314][D][lg-controller:1436]: Not sending, waiting for other controller or unit to send first
[21:29:55.309][D][lg-controller:1360]: update
[21:29:55.314][D][lg-controller:1436]: Not sending, waiting for other controller or unit to send first
[21:30:01.312][D][lg-controller:1360]: update
[21:30:01.313][D][lg-controller:1436]: Not sending, waiting for other controller or unit to send first
[21:30:07.316][D][lg-controller:1360]: update
[21:30:07.326][D][lg-controller:1436]: Not sending, waiting for other controller or unit to send first
[21:30:13.316][D][lg-controller:1360]: update
[21:30:13.318][D][lg-controller:1436]: Not sending, waiting for other controller or unit to send first
```

At the moment, the controller keeps waiting and does not transmit first, which makes me wonder whether the issue is related to:
1. the RX/TX wiring,
2. the use of an ESP32-WROOM-32 instead of the ESP32-C3 PCB,
3. the `is_slave_controller: true` setting,
4. or the compatibility of the **CM24 N14 / PREMTB001** combination with this implementation. [community.home-assistant](https://community.home-assistant.io/t/lg-ac-wired-controller-integration-via-esphome-esp32/582954?page=3)

Any feedback from people who have made this setup work would be very welcome, especially regarding:
- the exact wiring,
- the transceiver used,
- the correct RX/TX pin mapping,
- and whether the slave mode should be enabled for this type of installation. [github](https://github.com/JanM321/esphome-lg-controller/issues/34)

## Useful note
The project documentation says slave mode is experimental, and that if multiple controllers are connected to a single indoor unit, one controller must be the master while the others are slaves. [github](https://github.com/JanM321/esphome-lg-controller)
In one discussion, users reported that the slave mode was required when an LG wall controller and the ESPHome controller were connected in parallel. [github](https://github.com/JanM321/esphome-lg-controller/discussions/86)

Thank you for your help !
